Train Mode
[32m2022-02-07 14:48:42.963[39m | [1mINFO[22m | [90m/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/environment/level_utils.py:76[39m | Tokens in level ['-', 'T', 'X']
  0%|                                                                                                    | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main()
  File "main.py", line 71, in main
    generated_map = G.train(np.array(init_map), opt, i)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/train.py", line 140, in train
    loss = test_score(idx)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/train.py", line 32, in test_score
    model = DQN.load(f"./weights/trap_map_dqn_{idx+1}", env = env)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/stable_baselines3/common/base_class.py", line 577, in load
    data, params, pytorch_variables = load_from_zip_file(path, device=device)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/stable_baselines3/common/save_util.py", line 373, in load_from_zip_file
    load_path = open_path(load_path, "r", verbose=verbose, suffix="zip")
  File "/home/avsp/anaconda3/envs/gpn/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/stable_baselines3/common/save_util.py", line 232, in open_path_str
    return open_path(pathlib.Path(path), mode, verbose, suffix)
  File "/home/avsp/anaconda3/envs/gpn/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/stable_baselines3/common/save_util.py", line 284, in open_path_pathlib
    return open_path(path, mode, verbose, suffix)
  File "/home/avsp/anaconda3/envs/gpn/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/stable_baselines3/common/save_util.py", line 264, in open_path_pathlib
    raise error
  File "/home/avsp/Masa√ºst√º/GansNRoses/GansNRoses/stable_baselines3/common/save_util.py", line 256, in open_path_pathlib
    path = path.open("rb")
  File "/home/avsp/anaconda3/envs/gpn/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/home/avsp/anaconda3/envs/gpn/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/avsp/anaconda3/envs/gpn/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'weights/trap_map_dqn_1.zip'