2022-02-09 09:50:59,515 INFO    MainThread:25841 [internal.py:wandb_internal():91] W&B internal server running at pid: 25841, started at: 2022-02-09 09:50:59.515411
2022-02-09 09:50:59,519 INFO    WriterThread:25841 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220209_095058-26mofpxy/run-26mofpxy.wandb
2022-02-09 09:50:59,521 DEBUG   HandlerThread:25841 [handler.py:handle_request():124] handle_request: run_start
2022-02-09 09:51:01,009 DEBUG   HandlerThread:25841 [meta.py:__init__():39] meta init
2022-02-09 09:51:01,009 DEBUG   HandlerThread:25841 [meta.py:__init__():53] meta init done
2022-02-09 09:51:01,009 DEBUG   HandlerThread:25841 [meta.py:probe():210] probe
2022-02-09 09:51:01,016 DEBUG   HandlerThread:25841 [meta.py:_setup_git():200] setup git
2022-02-09 09:51:01,041 DEBUG   HandlerThread:25841 [meta.py:_setup_git():207] setup git done
2022-02-09 09:51:01,041 DEBUG   HandlerThread:25841 [meta.py:_save_pip():57] save pip
2022-02-09 09:51:01,042 DEBUG   HandlerThread:25841 [meta.py:_save_pip():71] save pip done
2022-02-09 09:51:01,042 DEBUG   HandlerThread:25841 [meta.py:_save_conda():78] save conda
2022-02-09 09:51:04,226 DEBUG   HandlerThread:25841 [meta.py:_save_conda():86] save conda done
2022-02-09 09:51:04,227 DEBUG   HandlerThread:25841 [meta.py:probe():252] probe done
2022-02-09 09:58:17,859 WARNING MainThread:25841 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-09 09:58:18,042 WARNING MainThread:25841 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-09 09:58:18,043 ERROR   MainThread:25841 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-09 09:58:18,304 INFO    WriterThread:25841 [datastore.py:close():288] close: output/wandb/offline-run-20220209_095058-26mofpxy/run-26mofpxy.wandb
2022-02-09 09:58:18,316 INFO    HandlerThread:25841 [handler.py:finish():658] shutting down handler
2022-02-09 09:58:18,397 INFO    MainThread:25841 [internal.py:handle_exit():78] Internal process exited
