2022-02-15 17:37:42,659 INFO    MainThread:22184 [internal.py:wandb_internal():91] W&B internal server running at pid: 22184, started at: 2022-02-15 17:37:42.659745
2022-02-15 17:37:42,663 INFO    WriterThread:22184 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220215_173741-1iarj6h4/run-1iarj6h4.wandb
2022-02-15 17:37:42,665 DEBUG   HandlerThread:22184 [handler.py:handle_request():124] handle_request: run_start
2022-02-15 17:37:44,192 DEBUG   HandlerThread:22184 [meta.py:__init__():39] meta init
2022-02-15 17:37:44,192 DEBUG   HandlerThread:22184 [meta.py:__init__():53] meta init done
2022-02-15 17:37:44,192 DEBUG   HandlerThread:22184 [meta.py:probe():210] probe
2022-02-15 17:37:44,199 DEBUG   HandlerThread:22184 [meta.py:_setup_git():200] setup git
2022-02-15 17:37:44,224 DEBUG   HandlerThread:22184 [meta.py:_setup_git():207] setup git done
2022-02-15 17:37:44,225 DEBUG   HandlerThread:22184 [meta.py:_save_pip():57] save pip
2022-02-15 17:37:44,226 DEBUG   HandlerThread:22184 [meta.py:_save_pip():71] save pip done
2022-02-15 17:37:44,226 DEBUG   HandlerThread:22184 [meta.py:_save_conda():78] save conda
2022-02-15 17:37:47,457 DEBUG   HandlerThread:22184 [meta.py:_save_conda():86] save conda done
2022-02-15 17:37:47,458 DEBUG   HandlerThread:22184 [meta.py:probe():252] probe done
2022-02-15 17:38:00,064 WARNING MainThread:22184 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-15 17:38:00,243 WARNING MainThread:22184 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-15 17:38:00,243 ERROR   MainThread:22184 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-15 17:38:00,466 INFO    WriterThread:22184 [datastore.py:close():288] close: output/wandb/offline-run-20220215_173741-1iarj6h4/run-1iarj6h4.wandb
2022-02-15 17:38:00,672 INFO    SenderThread:22184 [sender.py:finish():947] shutting down sender
2022-02-15 17:38:00,672 INFO    MainThread:22184 [internal.py:handle_exit():78] Internal process exited
