2022-02-13 19:57:54,592 INFO    MainThread:8413 [internal.py:wandb_internal():91] W&B internal server running at pid: 8413, started at: 2022-02-13 19:57:54.592508
2022-02-13 19:57:54,595 INFO    WriterThread:8413 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20220213_195753-2h1xacug/run-2h1xacug.wandb
2022-02-13 19:57:54,597 DEBUG   HandlerThread:8413 [handler.py:handle_request():124] handle_request: run_start
2022-02-13 19:57:56,559 DEBUG   HandlerThread:8413 [meta.py:__init__():39] meta init
2022-02-13 19:57:56,560 DEBUG   HandlerThread:8413 [meta.py:__init__():53] meta init done
2022-02-13 19:57:56,560 DEBUG   HandlerThread:8413 [meta.py:probe():210] probe
2022-02-13 19:57:56,567 DEBUG   HandlerThread:8413 [meta.py:_setup_git():200] setup git
2022-02-13 19:57:56,597 DEBUG   HandlerThread:8413 [meta.py:_setup_git():207] setup git done
2022-02-13 19:57:56,598 DEBUG   HandlerThread:8413 [meta.py:_save_pip():57] save pip
2022-02-13 19:57:56,598 DEBUG   HandlerThread:8413 [meta.py:_save_pip():71] save pip done
2022-02-13 19:57:56,598 DEBUG   HandlerThread:8413 [meta.py:_save_conda():78] save conda
2022-02-13 19:57:59,928 DEBUG   HandlerThread:8413 [meta.py:_save_conda():86] save conda done
2022-02-13 19:57:59,928 DEBUG   HandlerThread:8413 [meta.py:probe():252] probe done
2022-02-13 19:58:48,474 WARNING MainThread:8413 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-13 19:58:48,695 WARNING MainThread:8413 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-13 19:58:48,695 ERROR   MainThread:8413 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-13 19:58:49,029 INFO    MainThread:8413 [internal.py:handle_exit():78] Internal process exited
