2021-11-29 16:01:09,706 INFO    MainThread:23081 [internal.py:wandb_internal():91] W&B internal server running at pid: 23081, started at: 2021-11-29 16:01:09.706175
2021-11-29 16:01:09,709 INFO    WriterThread:23081 [datastore.py:open_for_write():80] open: output/wandb/offline-run-20211129_160108-3nu5f31n/run-3nu5f31n.wandb
2021-11-29 16:01:09,713 DEBUG   HandlerThread:23081 [handler.py:handle_request():124] handle_request: run_start
2021-11-29 16:01:11,346 DEBUG   HandlerThread:23081 [meta.py:__init__():39] meta init
2021-11-29 16:01:11,346 DEBUG   HandlerThread:23081 [meta.py:__init__():53] meta init done
2021-11-29 16:01:11,347 DEBUG   HandlerThread:23081 [meta.py:probe():210] probe
2021-11-29 16:01:11,353 DEBUG   HandlerThread:23081 [meta.py:_setup_git():200] setup git
2021-11-29 16:01:11,385 DEBUG   HandlerThread:23081 [meta.py:_setup_git():207] setup git done
2021-11-29 16:01:11,386 DEBUG   HandlerThread:23081 [meta.py:_save_pip():57] save pip
2021-11-29 16:01:11,388 DEBUG   HandlerThread:23081 [meta.py:_save_pip():71] save pip done
2021-11-29 16:01:11,388 DEBUG   HandlerThread:23081 [meta.py:_save_conda():78] save conda
2021-11-29 16:01:14,446 DEBUG   HandlerThread:23081 [meta.py:_save_conda():86] save conda done
2021-11-29 16:01:14,446 DEBUG   HandlerThread:23081 [meta.py:probe():252] probe done
2021-11-29 16:01:46,855 WARNING MainThread:23081 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-11-29 16:01:47,092 WARNING MainThread:23081 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-11-29 16:01:47,093 ERROR   MainThread:23081 [internal.py:wandb_internal():150] Internal process interrupted.
2021-11-29 16:01:47,723 INFO    SenderThread:23081 [sender.py:finish():947] shutting down sender
2021-11-29 16:01:47,789 INFO    WriterThread:23081 [datastore.py:close():288] close: output/wandb/offline-run-20211129_160108-3nu5f31n/run-3nu5f31n.wandb
2021-11-29 16:01:47,790 INFO    MainThread:23081 [internal.py:handle_exit():78] Internal process exited
